#!/bin/sh
set -e

case "$1" in
    remove|purge)
        # Remove rapt drop-in; leave the profile.d sourcing snippet
        # in Rprofile.site (other packages may use it)
        rm -f /etc/R/profile.d/rapt.R
        ;;
esac

#DEBHELPER#

exit 0
